#!/usr/bin/env python
"""Stage 6: emit an HDMI Hydra task config for a prepared motion.

Mirrors the structure of HDMI's shipped configs (cfg/task/G1/hdmi/*.yaml).
The contact offsets are the part you tune by hand: they say, in the OBJECT's
local frame, where the robot should make contact, and in the EEF's local frame
which point on the hand does the touching.

    python scripts/make_task_cfg.py --motion_dir ../HDMI/data/motion/data_for_sim/move_suitcase \
        --annotation annotations/move_suitcase.json --name MoveSuitcase
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parents[1]))
from hdmi_pipeline import paths

HDMI_ROOT = paths.HDMI_ROOT

TEMPLATE = """# @package task
# Generated by pipeline/scripts/make_task_cfg.py -- tune the contact offsets and
# randomization ranges before training.
defaults:
  - base/{hdmi_base}
  - _self_

name: {robot_prefix}{name}

viewer:
  env_spacing: 5.0
  lookat: [0., 0., 0.5]
  eye: [0.0, 3.0, 1.5]

robot:
  name: {robot_name}
  robot_type: {robot_type}

command:
  data_path: {data_path}
  root_body_name: "pelvis"
{joint_override}{extra_objects}  object_asset_name: "{asset}"
  object_body_name:  "{body}"
{object_joint}
  # Randomize where the object starts, so the policy does not memorize one pose.
  object_pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]

  # Desired contact points, in the OBJECT's local frame (one per end-effector).
  contact_target_pos_offset:
{contact_target}
  # Which point on each end-effector does the touching, in the EEF's local frame.
  contact_eef_pos_offset:
{contact_eef}

{action_override}reward:
  object_tracking:
    # eef_contact_exp has gain=5.0, so at weight 1.0 it scores ~3.5/step while
    # each tracking term is a product in [0,1] scoring 0.12-0.36 -- one contact
    # term outweighed all ten tracking terms combined (3.51 vs 2.67). At 0.5 the
    # object and tracking groups are balanced. Watch cum_lost_contact_steps if
    # you lower it further.
    eef_contact_exp: {{weight: {contact_weight}}}
{reward_tracking_override}
randomization:
  object_body_randomization:
    static_dynamic_friction_ratio_range: [1.0, 2.0]
    dynamic_friction_range: [0.3, 0.8]
    restitution_range: [0.0, 0.2]
    mass_range: [{mass_lo}, {mass_hi}]

  body_scale:
    name: "{body}"
    scale_range: [0.9, 1.1]
"""

TRACKING_TEMPLATE = """# @package task
# Generated by pipeline/scripts/make_task_cfg.py (mode=tracking).
# Pure whole-body motion tracking: no object, no contact. Use this for clips
# whose object has no simulatable asset, or that have no object at all.
defaults:
  - base/tracking-base
  - _self_

name: {robot_prefix}Track{name}

viewer:
  env_spacing: 3.0
  lookat: [0., 0., 0.5]
  eye: [0.0, 3.0, 1.5]

robot:
  name: {robot_name}
  robot_type: {robot_type}

command:
  data_path: {data_path}
  root_body_name: "pelvis"

  # Randomize the start pose so the policy does not memorize one placement.
  pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    yaw: [-0.1, 0.1]
"""

# (prefix, robot name, robot_type for hdmi mode, robot_type for tracking mode).
# Tracking tasks use the no-hand collision variant, matching HDMI's shipped
# cfg/task/G1/tracking/*.yaml.
ROBOT_PRESETS = {
    "g1": ("G1", "g1",
           "g1_29dof_rubberhand-feet_sphere-eef_box-body_capsule",
           "g1_29dof_nohand-feet_sphere"),
    "h1_2": ("H1_2", "h1_2", "h1_2_handless", "h1_2_handless"),
}


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--motion_dir", required=True)
    p.add_argument("--annotation", default=None)
    p.add_argument("--name", required=True, help="CamelCase task name, e.g. MoveSuitcase")
    p.add_argument("--robot", default="g1", choices=sorted(ROBOT_PRESETS))
    p.add_argument("--robot_type", default=None,
                   help="override the collision/end-effector variant, e.g. "
                        "g1_29dof_nohand-feet_sphere-eef_L-body_capsule")
    p.add_argument("--mode", default="auto", choices=["auto", "hdmi", "tracking"],
                   help="hdmi = object interaction; tracking = whole-body only. "
                        "auto picks tracking when the motion has no object bodies.")
    p.add_argument("--out", default=None, help="defaults to HDMI/cfg/task/<R>/hdmi/<snake>.yaml")
    p.add_argument("--mass_range", nargs=2, type=float, default=[1.0, 2.0])
    p.add_argument("--contact_weight", type=float, default=0.5,
                   help="weight for eef_contact_exp; 1.0 lets it dominate the "
                        "trajectory objective, 0.5 balances the two groups")
    p.add_argument("--half_width", type=float, default=0.17,
                   help="half-width used for the two default contact points")
    p.add_argument("--contact_height", type=float, default=0.14)
    args = p.parse_args()

    motion_dir = Path(args.motion_dir).resolve()
    meta = json.load(open(motion_dir / "meta.json"))

    # Robot links are named "*_link" (plus "pelvis"); anything else is an object.
    obj_bodies = [n for n in meta["body_names"]
                  if not n.endswith("_link") and n != "pelvis"]
    mode = args.mode
    if mode == "auto":
        mode = "hdmi" if (obj_bodies or args.annotation) else "tracking"
        print(f"[mode] auto -> {mode}"
              + (f" (object bodies: {obj_bodies})" if obj_bodies else " (no object bodies)"))
    if mode == "hdmi" and not obj_bodies:
        print("[warn] mode=hdmi but the motion has no object bodies; the "
              "RobotObjectTracking command expects one. Did you mean --mode tracking?")

    prefix, robot_name, robot_type_hdmi, robot_type_track = ROBOT_PRESETS[args.robot]

    # H1-2 has a single torso_joint where G1 has waist_yaw/roll/pitch, so the
    # base config's "waist_.*_joint" patterns match nothing and the command
    # constructor raises. Re-declare the affected lists.
    joint_override = action_override = reward_tracking_override = ""
    # H1-2 inherits a derived base (see scripts/make_h1_2_base.py); everything
    # waist-related is already resolved there, so no task-level overrides.
    hdmi_base = "hdmi-base-h1_2" if args.robot == "h1_2" else "hdmi-base"
    if False:   # superseded by the derived base
        JL = '["torso_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"]'
        joint_override = (
            '  # H1-2 has one torso_joint where G1 has waist_yaw/roll/pitch.\n'
            '  tracking_joint_names: ["torso_joint", ".*_hip_.*_joint", ".*_knee_joint", '
            '".*_ankle_.*_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"]\n')
        action_override = ("action:\n"
                           "  action_scaling:\n"
                           "    torso_joint: 0.55\n\n")
        reward_tracking_override = (
            "  tracking:\n"
            f"    joint_pos_tracking_product: {{joint_names: {JL}}}\n"
            f"    joint_vel_tracking_product: {{joint_names: {JL}}}\n"
            "  debug:\n"
            f"    joint_pos_error: {{joint_names: {JL}}}\n")
    robot_type = robot_type_hdmi if mode == "hdmi" else robot_type_track
    if args.robot_type:
        robot_type = args.robot_type
        print(f"[robot_type] override -> {robot_type}")

    snake = "".join("_" + c.lower() if c.isupper() else c for c in args.name).lstrip("_")
    try:
        data_path = motion_dir.relative_to(HDMI_ROOT).as_posix()
    except ValueError:
        data_path = motion_dir.as_posix()
        print(f"[warn] {motion_dir} is outside {HDMI_ROOT}; using an absolute data_path. "
              f"HDMI resolves relative paths from its repo root, so prefer putting "
              f"motions under HDMI/data/motion/.")

    if mode == "tracking":
        text = TRACKING_TEMPLATE.format(
            robot_prefix=prefix, name=args.name, robot_name=robot_name,
            robot_type=robot_type, data_path=data_path)
        subdir = "tracking"
        out = Path(args.out) if args.out else HDMI_ROOT / "cfg" / "task" / prefix / subdir / f"{snake}.yaml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        print(f"[done] {out}")
        print(f"\nTrain with:\n  cd {HDMI_ROOT}")
        print(f"  python scripts/train.py algo=ppo_roa_train task={prefix}/{subdir}/{snake}")
        print(f"\nVisualize the reference first:\n  python scripts/play.py algo=ppo_roa_train "
              f"task={prefix}/{subdir}/{snake} +task.command.replay_motion=true")
        return

    ann = json.load(open(args.annotation)) if args.annotation else {}
    obj = ann.get("object", {})
    asset = obj.get("asset") or (meta["body_names"][-1])
    body = obj.get("name") or asset

    extras = [e["name"] for e in ann.get("extra_objects", [])]
    extra_objects = (f'  extra_object_names: {json.dumps(extras)}\n' if extras else "")

    art = ann.get("articulation")
    object_joint = f'  object_joint_name: "{art["joint"]}"\n' if art else ""

    # The annotation owns the object's geometry, so if it declares contact
    # offsets use those; otherwise fall back to the symmetric default.
    def _fmt(rows, labels):
        return "\n".join(f"    - [{r[0]}, {r[1]}, {r[2]}]   # {lab}"
                         for r, lab in zip(rows, labels))

    if "contact_target_pos_offset" in ann:
        contact_target = _fmt(ann["contact_target_pos_offset"], ["left", "right"])
    else:
        contact_target = (
            f"    - [0, {args.half_width}, {args.contact_height}]   # left\n"
            f"    - [0,-{args.half_width}, {args.contact_height}]   # right"
        )
    if "contact_eef_pos_offset" in ann:
        contact_eef = _fmt(ann["contact_eef_pos_offset"], ["left", "right"])
    else:
        contact_eef = ("    - [0.05, 0.0, 0.0]  # left\n"
                       "    - [0.05, 0.0, 0.0]  # right")

    text = TEMPLATE.format(
        robot_prefix=prefix, name=args.name, robot_name=robot_name,
        robot_type=robot_type, data_path=data_path, extra_objects=extra_objects,
        asset=asset, body=body, object_joint=object_joint,
        contact_target=contact_target, contact_eef=contact_eef,
        joint_override=joint_override, action_override=action_override,
        hdmi_base=hdmi_base,
        reward_tracking_override=reward_tracking_override,
        mass_lo=args.mass_range[0], mass_hi=args.mass_range[1],
        contact_weight=args.contact_weight,
    )

    out = Path(args.out) if args.out else HDMI_ROOT / "cfg" / "task" / prefix / "hdmi" / f"{snake}.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)

    print(f"[done] {out}")
    print(f"\nTrain with:\n  cd {HDMI_ROOT}")
    print(f"  python scripts/train.py algo=ppo_roa_train task={prefix}/hdmi/{snake}")
    print(f"\nVisualize the reference first:\n  python scripts/play.py algo=ppo_roa_train "
          f"task={prefix}/hdmi/{snake} +task.command.replay_motion=true")


if __name__ == "__main__":
    main()
